### ISSUE TITLE
Doubled setting in "config.yml": auto_generate_proxy_classes

### ISSUE THREAD

**Issue by cmfcmf** [zikula/core#1402]
```
orm:
    auto_generate_proxy_classes: %kernel.debug%
    proxy_namespace: DoctrineProxy
    proxy_dir: %kernel.cache_dir%/doctrine/orm/DoctrineProxy
    default_entity_manager: default
    auto_generate_proxy_classes: true
```

@drak
