### ISSUE TITLE
Track Doctrine Bug 1057

### ISSUE THREAD

**Issue by craigh** [zikula/core#2185]
(this bug still exists in Doctrine, but shouldn't be a problem for us) [Doctrine bug 1057](http://www.doctrine-project.org/jira/browse/DBAL-1057) which requires DBAL to ping the DB to get version information. **workaround:** add `server_version` param to `config.yml`

``` yaml
doctrine:
    dbal:
        connections:
            default:
                ...
                server_version: 5.5
```

There is currently a [workaround](https://github.com/craigh/core/commit/bbb4349609e0931929142adb7963ab40b2575213) used in the core for this, but should Doctrine fix the bug we should correct the issue here also.

refs #2172
