### ISSUE TITLE
translation in 1.4.4 are not working anymore?

### ISSUE THREAD

**Issue by rallek** [zikula/core#3220]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 1.4.4 dev ci build 147
| PHP Version       | 5.5.30

### Expected behavior
using translation the same way than 1.4.3 should show the translated stings

### Actual behavior
that german is available is shown in the general settings but nothing is translated

### Steps to reproduce
* download the translation file of Sebastian (https://github.com/MrMontesa/german)
* place them into ``Zikula_Core-1.4.4/app/Resources/locale``
* try to configure that the german language is used

with a forme ci build this was working like expected (my last try was 127 I guess) 

From my point of view this is a blocker!

**Comment by rallek** [comment]
``locale: de`` is given correctly in ``custom_parameters.yml``. But even the translated field of e.g. ``site name`` is not used.

**Comment by craigh** [comment]
> try to configure that the german language is used

What does this mean?

Is this on install or after?

**Comment by rallek** [comment]
after. I installed without language pack. Next step was copying the language pack of Sebastion into the locale directory (as I did always before)

What does mean ``try to figure out that the german language is used``? Just see it ``site name`` becomes ``Seitenname`` for example.

**Comment by craigh** [comment]
Copy paste contents of dynamic/generated.yml

**Comment by rallek** [comment]
````
#This is a dynamically generated configuration file. Do not touch!

jms_i18n_routing:
    default_locale: de
    locales: [de, en]
    strategy: prefix_except_default
swiftmailer:
    transport: mail
    username: ''
    password: ''
    host: localhost
    port: 25
    encryption: null
    auth_mode: null
    delivery_addresses: []
    disable_delivery: false
parameters:
    zikula.session.name: _zsid
    multisites: { enabled: false, mainsiteurl: null, based_on_domains: null, protected.systemvars: [] }

````
