### ISSUE TITLE
[SortableColumns] still using legacy.css classes

### ISSUE THREAD

**Issue by craigh** [zikula/core#3757]
| Q                 | A
| ----------------- | ---
| Zikula Version    | 2.0.0
| PHP Version       | 5.5.26

### Expected behavior
sortable columns display headers correctly

### Actual behavior
no styling at all

### Steps to reproduce
load any list view implementing SortableColumns

The problem is that the Column class assumes availability of legacy css classes

    class Column
    {
        // ...
        const CSS_CLASS_UNSORTED = 'z-order-unsorted';
        const CSS_CLASS_ASCENDING = 'z-order-asc';
        const CSS_CLASS_DESCENDING = 'z-order-desc';

and the file `src/style/legacy.css` which defines these classes is no longer included with Core-2.0

**Comment by Guite** [comment]
Instead of removing the styles we should rather find a proper replacement for these arrow images.

Affects the generator, too.

**Comment by craigh** [comment]
the style definitions are already removed.

obvious replacements are font-awesome icons but placement of them following the text and maintaining the header style is not immediately obvious to me

**Comment by Guite** [comment]
Example:
```css
.z-order-asc:after,
.z-order-desc:after {
font-family: 'FontAwesome';
font-style: normal;
font-weight: normal;
}
.z-order-asc:after {
content: "\f106";
}
.z-order-down:after {
content: "\f107";
}
```

Of course other class names could also be used (without the `z-` prefix) if desired.
