### ISSUE TITLE
Available locales not properly updated

### ISSUE THREAD

**Issue by Guite** [zikula/core#4901]
@ThiloWitt copied translates into a 3.1 test site, went into the Settings module and saw all locales there. Afterwards this error occured: `Invalid configuration at path "jms_i18n_routing.default_locale": The default locale must be one of the configured locales.`.

The problems was caused by `config/packages/zikula_settings.yaml` which was not properly updated.
It contained:
```yaml
zikula_settings:
    locales:
        1: es
```
Things worked after he changed it to:
```yaml
zikula_settings:
    locales:
        1: en
        2: es 
```
